### ISSUE TITLE
validator class and methods

### ISSUE THREAD

**Issue by leonorader** [dernori/logiceval#1]
### ExpressionValidator 

when we get the input from the user we have to validate the expression itself

main method: isValid

- check for balanced parentheses
- check for valid symbols

**Comment by floppylab** [comment]
@grekton nice, but please add some javadoc comments, too!
one more thing: you could event split those two different checks into private methods, and the isValid method would only call these 2 (meybe it would be more readable)

**Comment by leonorader** [comment]
@grekton nice, but please add some javadoc comments, too!
one more thing: you could event split those two different checks into private methods, and the isValid method would only call these 2 (meybe it would be more readable)

**Comment by leonorader** [comment]
@grekton thanks, it is nice! 👍
