### ISSUE TITLE
logical methods

### ISSUE THREAD

**Issue by leonorader** [dernori/logiceval#4]
### Logical

creating a class containing our own methods to evaluate expressions

main methods: the operator functions 
- not
- and
- or
- implies

**Comment by floppylab** [comment]
I checked it, it is done. :)

**Comment by leonorader** [comment]
I checked it, it is done. :)

**Comment by leonorader** [comment]
@grekton  please add all the methods in this form too:
and ( boolean, boolean, boolean .... ) - so i would like to and several values...
+ it is similar to the main method's arguments... :)

**Comment by leonorader** [comment]
@grekton Thanks! :)
